"""Add user table

Revision ID: c134c871e11f
Revises: cc7951e0535e
Create Date: 2020-09-29 14:32:56.503229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c134c871e11f'
down_revision = 'cc7951e0535e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
